const mongoose=require ("mongoose");
const {Schema}=mongoose;
const orderSchema=new Schema({
  shippingDetails:{
    address:{
        type:String,
        required:true
    },
    city:{
        type:String,
        required:true
    },
    state:{
        type:String,
        required:true
    },

    country:{
        type:String,
        required:true
    },
    pincode:{
        type:Number,
        required:true
    },
    phoneNo:{
        type:Number,
        required:true
    }
  },

  orderItems:[
    {
        name:{
            type:String,
            required:true
        },
        price:{
            type:Number,
            required:true
        },
        quantity:{
            type:Number,
            required:true
        },
        image:{
            type:String,
            required:true
        },
        product:{
           type:mongoose.Schema.ObjectId,
           ref:"Product",
           required:true 
        }
    }
  ],
  user:{
        type:mongoose.Schema.ObjectId, 
        ref:"User",
        required:true
  },
  payment:{
        id:{
            type:String,
            required:true
        },
        status:{
            type:String,
            required:true
        }

  },
  paymentAt:{
    type:Date,
    required:true
  },
  totalPrice:{
    type:Number,
    required:true,
    default:0

  },
  taxPrice:{
    type:Number,
    required:true,
    default:0
  },
  shippingPrice:{
    type:Number,
    required:true,
    default:0
  },
  grandTotal:{
    type:Number,
    required:true
  },
  orderStatus:{
    type:String,
    required:true,
    default:"Processing"
  },
  deliveryDate: Date,
  createdAt:{
    type:Date,
    default:Date.now()
  }

})
module.exports=new mongoose.model("Orders", orderSchema);